// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsIxVIt-N-TiU1cTfc9B1jt5nvGtZwc94',
    appId: '1:890452892361:web:9bdafce8ad50b0f10f8b18',
    messagingSenderId: '890452892361',
    projectId: 'myflutterapp-4de84',
    authDomain: 'myflutterapp-4de84.firebaseapp.com',
    storageBucket: 'myflutterapp-4de84.appspot.com',
    measurementId: 'G-LD5Z0RK1C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtJZ1otoM9qj1n4kmTroog5dMjJwxEPUY',
    appId: '1:890452892361:android:aa3643b7a92ef53b0f8b18',
    messagingSenderId: '890452892361',
    projectId: 'myflutterapp-4de84',
    storageBucket: 'myflutterapp-4de84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA3Gsftl2Mb-yxQLRIcDMb0ILe8OcVYUc',
    appId: '1:890452892361:ios:74e391b623b9e9a70f8b18',
    messagingSenderId: '890452892361',
    projectId: 'myflutterapp-4de84',
    storageBucket: 'myflutterapp-4de84.appspot.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA3Gsftl2Mb-yxQLRIcDMb0ILe8OcVYUc',
    appId: '1:890452892361:ios:04185ca9eb90b76b0f8b18',
    messagingSenderId: '890452892361',
    projectId: 'myflutterapp-4de84',
    storageBucket: 'myflutterapp-4de84.appspot.com',
    iosBundleId: 'com.example.myNotes.RunnerTests',
  );
}
